
---
- name: Deploy website to Rocky Linux web server
  hosts: localhost
  become: true
  remote_user: root
  collections:
   - ansible.posix
  vars:
    website_dir: "/home/ec2-user/explore_california"
    target_directory: "/var/www/html"  # Default Apache web directory

  tasks:
    - name: Install web server
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Move website files to Apache directory
      ansible.builtin.shell: mv {{ website_dir }}/* {{ target_directory }}/

    - name: Ensure proper permissions for web files
      ansible.builtin.file:
        path: "{{ target_directory }}"
        state: directory
        owner: apache
        group: apache
        mode: '0755'
        recurse: yes

    - name: Restart the Apache web server to apply changes
      ansible.builtin.systemd:
        name: httpd
        state: restarted
