---
- name: Install prometheus
  hosts: monitor
  roles:
  - prometheus.prometheus.prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
              - 192.168.1.103:9100
        labels:
          env: lab2
